version: "3.4"
services:
  tdarr:
    container_name: deathprooftdarr
    build: .
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD129:/dev/dri/renderD128
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=Tiger-Heart
    volumes:
      - /mnt/Dockerspace/DTdarr/server:/app/server # change as needed
      - /mnt/Dockerspace/DTdarr/configs:/app/configs # change as needed
      - /mnt/Dockerspace/DTdarr/logs:/app/logs # change as needed
      - /mnt/Dockerspace/DTdarr/node:/app/Tdarr_Node # change as needed
      - /mnt:/mnt # change as needed
